### PR TITLE
Feature/import directives

### PR DESCRIPTION
**Pull request by giautm**
This PR is big, please review carefully

### CODE REVIEW

**Comment by giautm** [comment]
@kbrandwijk: Are you done with the review? :D 
cc @schickling

**Comment by kbrandwijk** [comment]
@giautm Sorry, been very busy. I'll try to run this today.

**Comment by giautm** [comment]
yah, i so busy too. :p

**Comment by kbrandwijk** [comment]
@giautm There's one missed branch in the code coverage. Could you please add a test case for it? It's for when a directive cannot be found:

https://22-111400047-gh.circle-artifacts.com/0/home/circleci/project/coverage/lcov-report/index.html

**Comment by kbrandwijk** [comment]
Thank you very much 🎉

**Pull request merged**
