### PR TITLE
Allow `.graphqls` file ending

### PR DESCRIPTION
**Pull request by anselmdk**

### CODE REVIEW

**Comment by Anurag-Mishra-Jykra** [comment]
Can you add `.gql` to the PR as well? I think it will be trivial to add. I didn't want to file a separate PR/issue for this.

**Comment by Van-Dame** [comment]
Can you please add `.gql` to the PR as well? It is a popular file extension for GraphQL files and it will be trivial to add. I didn't want to file a separate PR/issue for this.

**Comment by anselmdk** [comment]
@Van-Dame done

**Comment by anselmdk** [comment]
Makes sense, thanks for your input!

**Comment by schickling** [comment]
Thanks a lot for your thoughts on this @leebyron.

@anselmdk maybe you'd like to open a new PR that provides a new configuration option to make the file extension configurable?

**Pull request closed without merging**
